
micronaut.application.name=enterprise-erp-system
micronaut.server.port=9987

datasources.default.url=jdbc:sqlite:enterpriseerpsystem.db
datasources.default.username=postgres
datasources.default.password=postgres

teaql.ensureTable=true
teaql.contextClass=com.example.enterpriseerpsystem.CustomUserContext