
micronaut.application.name=payment-service
micronaut.server.port=9987

datasources.default.driverClassName=org.sqlite.JDBC
datasources.default.url=jdbc:sqlite:paymentservice.db
datasources.default.username=postgres
datasources.default.password=postgres

teaql.ensureTable=true
teaql.contextClass=com.example.paymentservice.CustomUserContext