import { Easing, interpolate, useCurrentFrame } from "remotion";
import { FadeUp } from "../components/FadeUp";
import { SceneFrame } from "../components/SceneFrame";
import { palette } from "../constants";

const values = [["01", "DataHub-grounded", "字段和治理说明来自企业目录"], ["02", "Local generation", "模型通过内网 loopback endpoint 生成"], ["03", "Runtime proof", "Java 与 Rust 安全出口真实脱敏"], ["04", "Fail closed", "上下文缺失时拒绝生成"]];

export const ClosingScene: React.FC = () => {
  const frame = useCurrentFrame();
  return <SceneFrame chapter="CLOSE" step="07 / 07"><div style={{ height: "100%", display: "flex", flexDirection: "column", justifyContent: "center" }}><FadeUp name="Closing title" delay={5}><div style={{ color: palette.cyan, fontFamily: "monospace", fontSize: 18, fontWeight: 800, letterSpacing: 3 }}>FROM GOVERNANCE TO RUNNABLE CODE</div><h2 style={{ margin: "16px 0 0", fontSize: 92, letterSpacing: -4.5 }}>从数据治理，到可运行代码</h2><p style={{ margin: "22px 0 0", color: palette.muted, fontSize: 32 }}>可追溯、可复现、默认安全，并适合企业内网的 Coding Agent 工作流。</p></FadeUp><div style={{ marginTop: 58, display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: 18 }}>{values.map(([number, title, detail], index) => <div key={number} style={{ minHeight: 230, padding: 26, border: `1px solid ${palette.line}`, borderRadius: 18, backgroundColor: "rgba(13,27,31,0.9)", opacity: interpolate(frame, [42 + index * 12, 64 + index * 12], [0, 1], { extrapolateLeft: "clamp", extrapolateRight: "clamp", easing: Easing.bezier(0.16, 1, 0.3, 1) }), transform: `translateY(${interpolate(frame, [42 + index * 12, 64 + index * 12], [30, 0], { extrapolateLeft: "clamp", extrapolateRight: "clamp", easing: Easing.bezier(0.16, 1, 0.3, 1) })}px)` }}><div style={{ color: palette.cyan, fontFamily: "monospace", fontSize: 17, fontWeight: 850 }}>{number}</div><div style={{ marginTop: 26, fontSize: 27, fontWeight: 820 }}>{title}</div><div style={{ marginTop: 13, color: palette.muted, fontSize: 18, lineHeight: 1.5 }}>{detail}</div></div>)}</div><FadeUp name="Closing footer" delay={118}><div style={{ marginTop: 38, display: "flex", justifyContent: "space-between", color: palette.green, fontFamily: "monospace", fontSize: 18, fontWeight: 800 }}><span>✓ MCP EVIDENCE</span><span>✓ MODEL EVAL</span><span>✓ JAVA + RUST TESTS</span><span>✓ NEGATIVE AGENT TEST</span></div></FadeUp></div></SceneFrame>;
};
