import { Easing, interpolate, useCurrentFrame } from "remotion";
import { FadeUp } from "../components/FadeUp";
import { SceneFrame } from "../components/SceneFrame";
import { palette } from "../constants";

const EvidenceCard: React.FC<{ language: string; marker: string; delay: number }> = ({ language, marker, delay }) => {
  const frame = useCurrentFrame();
  return <div style={{ padding: 26, border: `1px solid ${palette.line}`, borderRadius: 18, backgroundColor: "rgba(5,12,14,0.93)", opacity: interpolate(frame, [delay, delay + 22], [0, 1], { extrapolateLeft: "clamp", extrapolateRight: "clamp", easing: Easing.bezier(0.16, 1, 0.3, 1) }), transform: `translateY(${interpolate(frame, [delay, delay + 22], [28, 0], { extrapolateLeft: "clamp", extrapolateRight: "clamp", easing: Easing.bezier(0.16, 1, 0.3, 1) })}px)` }}><div style={{ display: "flex", justifyContent: "space-between" }}><span style={{ fontSize: 24, fontWeight: 820 }}>{language}</span><span style={{ color: palette.green, fontFamily: "monospace", fontSize: 13 }}>TEST PASS</span></div><div style={{ marginTop: 22, color: "#a9bab9", fontFamily: "monospace", fontSize: 16, lineHeight: 1.65 }}>{marker}</div><div style={{ marginTop: 20, display: "flex", gap: 18, color: palette.muted, fontFamily: "monospace", fontSize: 14 }}><span style={{ color: palette.green }}>masked=true</span><span>raw_present=false</span><span>currency visible</span></div></div>;
};

export const MaskingScene: React.FC = () => {
  const frame = useCurrentFrame();
  return <SceneFrame chapter="RUNTIME PROOF" step="05 / 07">
    <FadeUp name="Masking heading" delay={5}><div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-end", marginBottom: 28 }}><div><div style={{ color: palette.cyan, fontFamily: "monospace", fontSize: 18, fontWeight: 800, letterSpacing: 3 }}>RAW FORENSICS ≠ SAFE ANALYTICS</div><h2 style={{ margin: "14px 0 0", fontSize: 64, letterSpacing: -3 }}>One policy, enforced in two runtimes</h2></div><div style={{ color: palette.muted, fontSize: 22 }}>Generated metadata → SafeAuditEvent</div></div></FadeUp>
    <div style={{ display: "grid", gridTemplateColumns: "0.88fr 1.12fr", gap: 30, height: 620 }}>
      <FadeUp name="Audit flow" delay={24} style={{ height: "100%" }}><div style={{ height: "100%", padding: 30, border: `1px solid ${palette.line}`, borderRadius: 20, backgroundColor: "rgba(13,27,31,0.92)" }}><div style={{ color: palette.muted, fontFamily: "monospace", fontSize: 14, letterSpacing: 2 }}>PROCESS-LOCAL OBJECT FLOW</div><div style={{ marginTop: 26, padding: 22, borderRadius: 14, backgroundColor: "rgba(255,138,76,0.1)", border: `1px solid ${palette.orange}55` }}><div style={{ color: palette.orange, fontSize: 26, fontWeight: 800 }}>RawAuditEvent</div><div style={{ marginTop: 7, color: "#b89a8b", fontSize: 18 }}>Controlled forensics / privileged debugging</div></div><div style={{ height: 72, display: "grid", placeItems: "center", color: palette.cyan, fontSize: 30 }}>↓</div><div style={{ padding: 22, borderRadius: 14, border: `1px solid ${palette.cyan}`, backgroundColor: "rgba(79,225,209,0.1)", boxShadow: `0 0 46px rgba(79,225,209,${interpolate(frame, [90, 120, 180, 210], [0.05, 0.2, 0.2, 0.05], { extrapolateLeft: "clamp", extrapolateRight: "clamp" })})` }}><div style={{ color: palette.cyan, fontSize: 26, fontWeight: 800 }}>_audit_mask_fields</div><div style={{ marginTop: 7, fontFamily: "monospace", fontSize: 18 }}>payment_account</div></div><div style={{ height: 72, display: "grid", placeItems: "center", color: palette.cyan, fontSize: 30 }}>↓</div><div style={{ padding: 22, borderRadius: 14, backgroundColor: "rgba(114,230,166,0.09)", border: `1px solid ${palette.green}55` }}><div style={{ color: palette.green, fontSize: 26, fontWeight: 800 }}>SafeAuditEvent</div><div style={{ marginTop: 7, color: "#9ab9aa", fontSize: 18 }}>OpenSearch / OpenTelemetry</div></div></div></FadeUp>
      <div style={{ display: "grid", gap: 20, alignContent: "center" }}><EvidenceCard language="Java" delay={55} marker="JAVA_MASKING_EVIDENCE entity=PaymentTransaction field=paymentAccount reason=_audit_mask_fields" /><EvidenceCard language="Rust" delay={110} marker="MASKING_EVIDENCE entity=PaymentTransaction field=payment_account reason=_audit_mask_fields" /><FadeUp name="Masking boundary" delay={155}><div style={{ padding: "20px 24px", borderRadius: 14, backgroundColor: "rgba(79,225,209,0.08)", color: palette.cyan, fontSize: 21, fontWeight: 720 }}>Masking happens before safe output — raw forensic logging remains a separate privileged path.</div></FadeUp></div>
    </div>
  </SceneFrame>;
};
