
quarkus.application.name=payment-service
quarkus.http.port=9987

quarkus.datasource.jdbc.driver=org.sqlite.JDBC
quarkus.datasource.jdbc.url=jdbc:sqlite:paymentservice.db
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres

teaql.ensureTable=true
teaql.contextClass=com.example.paymentservice.CustomUserContext